### ISSUE TITLE
Language picker

### ISSUE THREAD

**Issue by bagilevi** [EasyGerman/interactive-transcript#3]
enable translation to other languages than English

**Comment by bagilevi** [comment]
![Screenshot 2020-06-07 at 11 26 30](https://user-images.githubusercontent.com/16766/83965151-d7b71880-a8b1-11ea-9ae3-785378bc7661.png)

---

![Screenshot 2020-06-07 at 11 26 42](https://user-images.githubusercontent.com/16766/83965155-da197280-a8b1-11ea-8306-65e526c9a815.png)

**Comment by EasyGerman** [comment]
Wohoo awesome! Would it be easy to remove "German" from the list, since that doesn't really make sense? Also, I have some small ideas to improve design:
- Equalize space at the top and bottom
- Make the green box gray (it's just too much green otherwise in my opinion)
- "Tranlsation language:" in bold
- DeepL-disclaimer even smaller and in gray
<img width="357" alt="Screenshot 2020-06-08 11 11 31" src="https://user-images.githubusercontent.com/63775646/84039300-5b9bfe00-a9a1-11ea-96d9-4ca6f7c56880.png">

What do you think?
