### ISSUE TITLE
Add vocab slides

### ISSUE THREAD

**Issue by bagilevi** [EasyGerman/interactive-transcript#7]
Here's an experiment using the video:

![Screen Shot 2020-04-16 at 21 49 19](https://user-images.githubusercontent.com/16766/79500078-2ff93900-802c-11ea-9bd1-d9b8ef4d4b55.png)

The issue is that I couldn't find a way to programmatically embed the video from Google Drive (I had to manually download and use the local file). We might need a different way to get the video directly, or perhaps get the vocab helper slides in a different format (images, or computer-parsable text file)

**Comment by natashaw** [comment]
Hi Levente! Thanks for developing this transcript player. I'm interested to contribute somehow to this project, which I find to be interesting as I'm also one of Easy German patreon.

On integrating the Vokabelhilfe, wouldn't it actually be an easier solution to use the CSV file instead of the video and embed that into the line which contains that word itself? That, in my opinion, can be on top of the translation feature or in place of it.

**Comment by bagilevi** [comment]
Hi @natashaw – Thanks for the idea. It would be easier to parse the CSV, but I think it would be too difficult to match it to the correct word, since most of the time they're used in a different form than the "dictionary" version, e.g. in plural, in declined form, separated, etc.

**Comment by EasyGerman** [comment]
People are asking specifically for a combined transcript scroller and vocabulary helper. I'm not sure how to solve the problem, but here are some ideas/questions:

- If the video can't be pulled from Google Drive, can we just upload it somewhere else? The video files are between 50 and 200 MB each, so we'd need 1 GB of storage per month max. I'm unsure how much traffic there would be. What about a dedicated YouTube account for this, where we publish the videos as "unlisted"? (Unlisted videos _can_ be embedded on websites.) We'd still want people to be able to download them, thought, so we'd have to do both.

Maybe the same functionality can be achieved with other files/data instead of the video? Maybe it would even be better, since the square aspect ration of the Vokabelhilfe is really meant for podcast apps? (How would the example Levente posted above fit on a mobile screen?)

Here are some of the other files and more info from our production workflow in case any of this helps (this is all from EGP 30):
- The [Vokabelhilfe.txt](https://github.com/EasyGerman/interactive-transcript/files/4557575/Vokabelhilfe.txt) file has all of the vocabulary and translations, formatted as Photoshop variables. (We import this file into Photoshop to generate the chapter files.)
- The image changes every full minute, with minor exceptions: The first one starts after the intro (around minute 0:14 usually) and when a new segment begins _almost_ on the minute-mark, we  move the switching of the image to that mark, so the regular chapter mark (for the segment) doubles as the chapter mark for the new Vokabelhilfe image. For example, on episode 30, the image for Vokabelhilfe 49 comes in at 00:47:52.569 already instead of 00:48. Also, since there is no Vokabelhilfe for the Bonus at the end, it goes back to the cover there. Here is the chapter file for EGP 30 (this is automatically generated for each episode):
[egp30_Chapters-File.chapters.txt](https://github.com/EasyGerman/interactive-transcript/files/4557595/egp30_Chapters-File.chapters.txt)
(For simplicity's sake, it would also be "good enough" if a new image comes in at each full minute, starting with image 1 at minute 0:00, image 2 at minute 1:00 and so on.)
- Here are the raw chapter images as PNGs for episode 30:
[egp30_images.zip](https://github.com/EasyGerman/interactive-transcript/files/4557605/egp30_images.zip)

Thanks! Manuel

**Comment by bagilevi** [comment]
@EasyGerman 
I managed to get images and chapter timings out of the mp3 file, so we can either display the image or display the words from the plain text using the chapter timings from the mp3.

For mobile, I think we can add a button to toggle between the transcript scroller and the vocabulary helper.

I also plan to do some experimentation on locating the words in vocabulary helper in the transcript based on part of the word.

**Comment by EasyGerman** [comment]
@bagilevi If you can pull the chapter images from the mp3, that's probably the easiest in terms of our workflow, since we won't have to upload the plain text anywhere. Your second idea might require that file though? A toggle to switch between with and without vocabulary helper sounds great!

**Comment by bagilevi** [comment]
Done

**Comment by sandinosaso** [comment]
I know this issue was closed but I feel the same as @natashaw that having the vocable help in a text could better improve the experience and I think images are ok for a podcast app but not for this interactive transcript app.

I played a little with this idea, what happens to me is that when reading the translations I can not keep good track of the vocable words when they are used in the text. It would be great to have them like in bold or somehow bigger fonts, so I can see when it used and what it means without having to stop/pause stop/pause.

I find it challenging because you have the whole list of vocabulary words, not the timestamps...if the file that contains the vocabulary would have the times that functionality would be possible. The images are not useful in this interactive transcript (they are useful in the podcast apps but not here).

Something like this would help: 
```
[00:00] der Korken - the cork
[00:00] mitbringen - bring along
....
...
[00:59] hilfe - help
[00:59] hilfe - help
[00:59] hilfe - help
[00:59] hilfe - help
[00:59] hilfe - help
....
....
[03:00] hilfe - help
[03:00] hilfe - help

```

This way we know the exact 9-10 or more words that are in each minute, having the whole list we can not say what is currently going on.

I played with this idea, so I am doing bold in words that are in the vocabulary but I can not mark only words that are present in the current minute but I compare with the whole list of words in the vocabulary (not ideal by performance and not the context - maybe the word appears in this moment but the vocable Hilfe was 3 minutes ago).

@bagilevi @natashaw @EasyGerman Not sure what do you think about it, I think it could be very useful at least for me.

I would attach a gif of what I am thinking about.

![1_Los_geht_s_](https://user-images.githubusercontent.com/466105/82928197-e7e50480-9f4f-11ea-9ba2-2deb39367e2f.gif)

This is just an idea, we could improve, of course, there is the limitation you mentioned that some times words do not appear in the text exactly as in the vocabulary list but this can be solved easily by just adding this in the file (like the word as it appears, is just a matter of adding a little more information to that text or rtf file)

**Comment by sandinosaso** [comment]
I will create a new issue so maybe it gets noticed by you guys.
